[variables]
NODE_ENV = "production"
NPM_CONFIG_CACHE = "/tmp/.npm-cache"
NIXPACKS_NO_CACHE = "1"

[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = [
  "npm config set cache /tmp/.npm-cache",
  "npm ci --omit=dev --prefer-offline --no-audit"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "npm run railway:start"