[variables]
NODE_ENV = "production"
NPM_CONFIG_CACHE = "/tmp/.npm"

[phases.build]
cmds = [
  "npm config set cache /tmp/.npm",
  "npm ci --production=false --prefer-offline --no-audit --no-optional",
  "npm run build",
  "npm prune --production",
  "find . -name '*.map' -delete || true",
  "find . -name '*.md' -not -path './node_modules/*' -delete || true",
  "find . -name 'docs' -type d -not -path './node_modules/*' -exec rm -rf {} + || true",
  "find . -name '__tests__' -type d -exec rm -rf {} + || true",
  "find . -name '*.test.*' -delete || true",
  "find . -name '*.spec.*' -delete || true",
  "rm -rf client/src server/src tests cypress scripts docs || true"
]